/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LojaSlugRouteImport } from './routes/loja/$slug'
import { Route as LojaSlugIndexRouteImport } from './routes/loja/$slug/index'
import { Route as LojaSlugCampanhasIndexRouteImport } from './routes/loja/$slug/campanhas/index'
import { Route as LojaSlugCampanhasCampanhaRouteImport } from './routes/loja/$slug/campanhas/$campanha'
import { Route as LojaSlugPProdutoRouteImport } from './routes/loja/$slug/p/$produto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugIndexRoute = LojaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugCampanhasIndexRoute = LojaSlugCampanhasIndexRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugCampanhasCampanhaRoute =
  LojaSlugCampanhasCampanhaRouteImport.update({
    id: '/campanhas/$campanha',
    path: '/campanhas/$campanha',
    getParentRoute: () => LojaSlugRoute,
  } as any)
const LojaSlugPProdutoRoute = LojaSlugPProdutoRouteImport.update({
  id: '/p/$produto',
  path: '/p/$produto',
  getParentRoute: () => LojaSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lojas': typeof LojasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/campanhas/$campanha': typeof LojaSlugCampanhasCampanhaRoute
  '/loja/$slug/p/$produto': typeof LojaSlugPProdutoRoute
  '/loja/$slug/campanhas/': typeof LojaSlugCampanhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lojas': typeof LojasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/loja/$slug': typeof LojaSlugIndexRoute
  '/loja/$slug/campanhas/$campanha': typeof LojaSlugCampanhasCampanhaRoute
  '/loja/$slug/p/$produto': typeof LojaSlugPProdutoRoute
  '/loja/$slug/campanhas': typeof LojaSlugCampanhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lojas': typeof LojasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/campanhas/$campanha': typeof LojaSlugCampanhasCampanhaRoute
  '/loja/$slug/p/$produto': typeof LojaSlugPProdutoRoute
  '/loja/$slug/campanhas/': typeof LojaSlugCampanhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lojas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/loja/$slug'
    | '/loja/$slug/'
    | '/loja/$slug/campanhas/$campanha'
    | '/loja/$slug/p/$produto'
    | '/loja/$slug/campanhas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lojas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/loja/$slug'
    | '/loja/$slug/campanhas/$campanha'
    | '/loja/$slug/p/$produto'
    | '/loja/$slug/campanhas'
  id:
    | '__root__'
    | '/'
    | '/lojas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/loja/$slug'
    | '/loja/$slug/'
    | '/loja/$slug/campanhas/$campanha'
    | '/loja/$slug/p/$produto'
    | '/loja/$slug/campanhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LojasRoute: typeof LojasRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug/': {
      id: '/loja/$slug/'
      path: '/'
      fullPath: '/loja/$slug/'
      preLoaderRoute: typeof LojaSlugIndexRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/campanhas/': {
      id: '/loja/$slug/campanhas/'
      path: '/campanhas'
      fullPath: '/loja/$slug/campanhas/'
      preLoaderRoute: typeof LojaSlugCampanhasIndexRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/campanhas/$campanha': {
      id: '/loja/$slug/campanhas/$campanha'
      path: '/campanhas/$campanha'
      fullPath: '/loja/$slug/campanhas/$campanha'
      preLoaderRoute: typeof LojaSlugCampanhasCampanhaRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/p/$produto': {
      id: '/loja/$slug/p/$produto'
      path: '/p/$produto'
      fullPath: '/loja/$slug/p/$produto'
      preLoaderRoute: typeof LojaSlugPProdutoRouteImport
      parentRoute: typeof LojaSlugRoute
    }
  }
}

interface LojaSlugRouteChildren {
  LojaSlugIndexRoute: typeof LojaSlugIndexRoute
  LojaSlugCampanhasCampanhaRoute: typeof LojaSlugCampanhasCampanhaRoute
  LojaSlugPProdutoRoute: typeof LojaSlugPProdutoRoute
  LojaSlugCampanhasIndexRoute: typeof LojaSlugCampanhasIndexRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugIndexRoute: LojaSlugIndexRoute,
  LojaSlugCampanhasCampanhaRoute: LojaSlugCampanhasCampanhaRoute,
  LojaSlugPProdutoRoute: LojaSlugPProdutoRoute,
  LojaSlugCampanhasIndexRoute: LojaSlugCampanhasIndexRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LojasRoute: LojasRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LojaSlugRoute: LojaSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
