/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as NovaLojaRouteImport } from './routes/nova-loja'
import { Route as PlataformaRouteImport } from './routes/plataforma'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ConviteTokenRouteImport } from './routes/convite/$token'
import { Route as GestaoSlugRouteImport } from './routes/gestao/$slug'
import { Route as LojaSlugRouteImport } from './routes/loja/$slug'
import { Route as GestaoSlugIndexRouteImport } from './routes/gestao/$slug/index'
import { Route as GestaoSlugAgendaRouteImport } from './routes/gestao/$slug/agenda'
import { Route as GestaoSlugCampanhasRouteImport } from './routes/gestao/$slug/campanhas'
import { Route as GestaoSlugConfiguracoesRouteImport } from './routes/gestao/$slug/configuracoes'
import { Route as GestaoSlugDoacoesRouteImport } from './routes/gestao/$slug/doacoes'
import { Route as GestaoSlugEncomendasRouteImport } from './routes/gestao/$slug/encomendas'
import { Route as GestaoSlugEquipeRouteImport } from './routes/gestao/$slug/equipe'
import { Route as GestaoSlugExtratoRouteImport } from './routes/gestao/$slug/extrato'
import { Route as GestaoSlugPedidosRouteImport } from './routes/gestao/$slug/pedidos'
import { Route as GestaoSlugProdutosRouteImport } from './routes/gestao/$slug/produtos'
import { Route as GestaoSlugRecebimentoRouteImport } from './routes/gestao/$slug/recebimento'
import { Route as GestaoSlugRepassesRouteImport } from './routes/gestao/$slug/repasses'
import { Route as GestaoSlugResultadoRouteImport } from './routes/gestao/$slug/resultado'
import { Route as LojaSlugIndexRouteImport } from './routes/loja/$slug/index'
import { Route as LojaSlugComprarRouteImport } from './routes/loja/$slug/comprar'
import { Route as LojaSlugDoarRouteImport } from './routes/loja/$slug/doar'
import { Route as LojaSlugCampanhasIndexRouteImport } from './routes/loja/$slug/campanhas/index'
import { Route as LojaSlugCampanhasCampanhaRouteImport } from './routes/loja/$slug/campanhas/$campanha'
import { Route as LojaSlugEEventoRouteImport } from './routes/loja/$slug/e/$evento'
import { Route as LojaSlugPProdutoRouteImport } from './routes/loja/$slug/p/$produto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaLojaRoute = NovaLojaRouteImport.update({
  id: '/nova-loja',
  path: '/nova-loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaRoute = PlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoSlugRoute = GestaoSlugRouteImport.update({
  id: '/gestao/$slug',
  path: '/gestao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoSlugIndexRoute = GestaoSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugAgendaRoute = GestaoSlugAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugCampanhasRoute = GestaoSlugCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugConfiguracoesRoute = GestaoSlugConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugDoacoesRoute = GestaoSlugDoacoesRouteImport.update({
  id: '/doacoes',
  path: '/doacoes',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugEncomendasRoute = GestaoSlugEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugEquipeRoute = GestaoSlugEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugExtratoRoute = GestaoSlugExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugPedidosRoute = GestaoSlugPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugProdutosRoute = GestaoSlugProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugRecebimentoRoute = GestaoSlugRecebimentoRouteImport.update({
  id: '/recebimento',
  path: '/recebimento',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugRepassesRoute = GestaoSlugRepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const GestaoSlugResultadoRoute = GestaoSlugResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => GestaoSlugRoute,
} as any)
const LojaSlugIndexRoute = LojaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugComprarRoute = LojaSlugComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugDoarRoute = LojaSlugDoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugCampanhasIndexRoute = LojaSlugCampanhasIndexRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugCampanhasCampanhaRoute =
  LojaSlugCampanhasCampanhaRouteImport.update({
    id: '/campanhas/$campanha',
    path: '/campanhas/$campanha',
    getParentRoute: () => LojaSlugRoute,
  } as any)
const LojaSlugEEventoRoute = LojaSlugEEventoRouteImport.update({
  id: '/e/$evento',
  path: '/e/$evento',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugPProdutoRoute = LojaSlugPProdutoRouteImport.update({
  id: '/p/$produto',
  path: '/p/$produto',
  getParentRoute: () => LojaSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/lojas': typeof LojasRoute
  '/nova-loja': typeof NovaLojaRoute
  '/plataforma': typeof PlataformaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/gestao/$slug': typeof GestaoSlugRouteWithChildren
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/gestao/$slug/agenda': typeof GestaoSlugAgendaRoute
  '/gestao/$slug/campanhas': typeof GestaoSlugCampanhasRoute
  '/gestao/$slug/configuracoes': typeof GestaoSlugConfiguracoesRoute
  '/gestao/$slug/doacoes': typeof GestaoSlugDoacoesRoute
  '/gestao/$slug/encomendas': typeof GestaoSlugEncomendasRoute
  '/gestao/$slug/equipe': typeof GestaoSlugEquipeRoute
  '/gestao/$slug/extrato': typeof GestaoSlugExtratoRoute
  '/gestao/$slug/pedidos': typeof GestaoSlugPedidosRoute
  '/gestao/$slug/produtos': typeof GestaoSlugProdutosRoute
  '/gestao/$slug/recebimento': typeof GestaoSlugRecebimentoRoute
  '/gestao/$slug/repasses': typeof GestaoSlugRepassesRoute
  '/gestao/$slug/resultado': typeof GestaoSlugResultadoRoute
  '/loja/$slug/comprar': typeof LojaSlugComprarRoute
  '/loja/$slug/doar': typeof LojaSlugDoarRoute
  '/gestao/$slug/': typeof GestaoSlugIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/campanhas/$campanha': typeof LojaSlugCampanhasCampanhaRoute
  '/loja/$slug/e/$evento': typeof LojaSlugEEventoRoute
  '/loja/$slug/p/$produto': typeof LojaSlugPProdutoRoute
  '/loja/$slug/campanhas/': typeof LojaSlugCampanhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/lojas': typeof LojasRoute
  '/nova-loja': typeof NovaLojaRoute
  '/plataforma': typeof PlataformaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/gestao/$slug/agenda': typeof GestaoSlugAgendaRoute
  '/gestao/$slug/campanhas': typeof GestaoSlugCampanhasRoute
  '/gestao/$slug/configuracoes': typeof GestaoSlugConfiguracoesRoute
  '/gestao/$slug/doacoes': typeof GestaoSlugDoacoesRoute
  '/gestao/$slug/encomendas': typeof GestaoSlugEncomendasRoute
  '/gestao/$slug/equipe': typeof GestaoSlugEquipeRoute
  '/gestao/$slug/extrato': typeof GestaoSlugExtratoRoute
  '/gestao/$slug/pedidos': typeof GestaoSlugPedidosRoute
  '/gestao/$slug/produtos': typeof GestaoSlugProdutosRoute
  '/gestao/$slug/recebimento': typeof GestaoSlugRecebimentoRoute
  '/gestao/$slug/repasses': typeof GestaoSlugRepassesRoute
  '/gestao/$slug/resultado': typeof GestaoSlugResultadoRoute
  '/loja/$slug/comprar': typeof LojaSlugComprarRoute
  '/loja/$slug/doar': typeof LojaSlugDoarRoute
  '/gestao/$slug': typeof GestaoSlugIndexRoute
  '/loja/$slug': typeof LojaSlugIndexRoute
  '/loja/$slug/campanhas/$campanha': typeof LojaSlugCampanhasCampanhaRoute
  '/loja/$slug/e/$evento': typeof LojaSlugEEventoRoute
  '/loja/$slug/p/$produto': typeof LojaSlugPProdutoRoute
  '/loja/$slug/campanhas': typeof LojaSlugCampanhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/lojas': typeof LojasRoute
  '/nova-loja': typeof NovaLojaRoute
  '/plataforma': typeof PlataformaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/gestao/$slug': typeof GestaoSlugRouteWithChildren
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/gestao/$slug/agenda': typeof GestaoSlugAgendaRoute
  '/gestao/$slug/campanhas': typeof GestaoSlugCampanhasRoute
  '/gestao/$slug/configuracoes': typeof GestaoSlugConfiguracoesRoute
  '/gestao/$slug/doacoes': typeof GestaoSlugDoacoesRoute
  '/gestao/$slug/encomendas': typeof GestaoSlugEncomendasRoute
  '/gestao/$slug/equipe': typeof GestaoSlugEquipeRoute
  '/gestao/$slug/extrato': typeof GestaoSlugExtratoRoute
  '/gestao/$slug/pedidos': typeof GestaoSlugPedidosRoute
  '/gestao/$slug/produtos': typeof GestaoSlugProdutosRoute
  '/gestao/$slug/recebimento': typeof GestaoSlugRecebimentoRoute
  '/gestao/$slug/repasses': typeof GestaoSlugRepassesRoute
  '/gestao/$slug/resultado': typeof GestaoSlugResultadoRoute
  '/loja/$slug/comprar': typeof LojaSlugComprarRoute
  '/loja/$slug/doar': typeof LojaSlugDoarRoute
  '/gestao/$slug/': typeof GestaoSlugIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/campanhas/$campanha': typeof LojaSlugCampanhasCampanhaRoute
  '/loja/$slug/e/$evento': typeof LojaSlugEEventoRoute
  '/loja/$slug/p/$produto': typeof LojaSlugPProdutoRoute
  '/loja/$slug/campanhas/': typeof LojaSlugCampanhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conta'
    | '/criar-conta'
    | '/entrar'
    | '/lojas'
    | '/nova-loja'
    | '/plataforma'
    | '/recuperar-senha'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/convite/$token'
    | '/gestao/$slug'
    | '/loja/$slug'
    | '/gestao/$slug/agenda'
    | '/gestao/$slug/campanhas'
    | '/gestao/$slug/configuracoes'
    | '/gestao/$slug/doacoes'
    | '/gestao/$slug/encomendas'
    | '/gestao/$slug/equipe'
    | '/gestao/$slug/extrato'
    | '/gestao/$slug/pedidos'
    | '/gestao/$slug/produtos'
    | '/gestao/$slug/recebimento'
    | '/gestao/$slug/repasses'
    | '/gestao/$slug/resultado'
    | '/loja/$slug/comprar'
    | '/loja/$slug/doar'
    | '/gestao/$slug/'
    | '/loja/$slug/'
    | '/loja/$slug/campanhas/$campanha'
    | '/loja/$slug/e/$evento'
    | '/loja/$slug/p/$produto'
    | '/loja/$slug/campanhas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conta'
    | '/criar-conta'
    | '/entrar'
    | '/lojas'
    | '/nova-loja'
    | '/plataforma'
    | '/recuperar-senha'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/convite/$token'
    | '/gestao/$slug/agenda'
    | '/gestao/$slug/campanhas'
    | '/gestao/$slug/configuracoes'
    | '/gestao/$slug/doacoes'
    | '/gestao/$slug/encomendas'
    | '/gestao/$slug/equipe'
    | '/gestao/$slug/extrato'
    | '/gestao/$slug/pedidos'
    | '/gestao/$slug/produtos'
    | '/gestao/$slug/recebimento'
    | '/gestao/$slug/repasses'
    | '/gestao/$slug/resultado'
    | '/loja/$slug/comprar'
    | '/loja/$slug/doar'
    | '/gestao/$slug'
    | '/loja/$slug'
    | '/loja/$slug/campanhas/$campanha'
    | '/loja/$slug/e/$evento'
    | '/loja/$slug/p/$produto'
    | '/loja/$slug/campanhas'
  id:
    | '__root__'
    | '/'
    | '/conta'
    | '/criar-conta'
    | '/entrar'
    | '/lojas'
    | '/nova-loja'
    | '/plataforma'
    | '/recuperar-senha'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/convite/$token'
    | '/gestao/$slug'
    | '/loja/$slug'
    | '/gestao/$slug/agenda'
    | '/gestao/$slug/campanhas'
    | '/gestao/$slug/configuracoes'
    | '/gestao/$slug/doacoes'
    | '/gestao/$slug/encomendas'
    | '/gestao/$slug/equipe'
    | '/gestao/$slug/extrato'
    | '/gestao/$slug/pedidos'
    | '/gestao/$slug/produtos'
    | '/gestao/$slug/recebimento'
    | '/gestao/$slug/repasses'
    | '/gestao/$slug/resultado'
    | '/loja/$slug/comprar'
    | '/loja/$slug/doar'
    | '/gestao/$slug/'
    | '/loja/$slug/'
    | '/loja/$slug/campanhas/$campanha'
    | '/loja/$slug/e/$evento'
    | '/loja/$slug/p/$produto'
    | '/loja/$slug/campanhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaRoute: typeof ContaRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  LojasRoute: typeof LojasRoute
  NovaLojaRoute: typeof NovaLojaRoute
  PlataformaRoute: typeof PlataformaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  GestaoSlugRoute: typeof GestaoSlugRouteWithChildren
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-loja': {
      id: '/nova-loja'
      path: '/nova-loja'
      fullPath: '/nova-loja'
      preLoaderRoute: typeof NovaLojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma': {
      id: '/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof PlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/$slug': {
      id: '/gestao/$slug'
      path: '/gestao/$slug'
      fullPath: '/gestao/$slug'
      preLoaderRoute: typeof GestaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/$slug/': {
      id: '/gestao/$slug/'
      path: '/'
      fullPath: '/gestao/$slug/'
      preLoaderRoute: typeof GestaoSlugIndexRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/agenda': {
      id: '/gestao/$slug/agenda'
      path: '/agenda'
      fullPath: '/gestao/$slug/agenda'
      preLoaderRoute: typeof GestaoSlugAgendaRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/campanhas': {
      id: '/gestao/$slug/campanhas'
      path: '/campanhas'
      fullPath: '/gestao/$slug/campanhas'
      preLoaderRoute: typeof GestaoSlugCampanhasRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/configuracoes': {
      id: '/gestao/$slug/configuracoes'
      path: '/configuracoes'
      fullPath: '/gestao/$slug/configuracoes'
      preLoaderRoute: typeof GestaoSlugConfiguracoesRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/doacoes': {
      id: '/gestao/$slug/doacoes'
      path: '/doacoes'
      fullPath: '/gestao/$slug/doacoes'
      preLoaderRoute: typeof GestaoSlugDoacoesRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/encomendas': {
      id: '/gestao/$slug/encomendas'
      path: '/encomendas'
      fullPath: '/gestao/$slug/encomendas'
      preLoaderRoute: typeof GestaoSlugEncomendasRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/equipe': {
      id: '/gestao/$slug/equipe'
      path: '/equipe'
      fullPath: '/gestao/$slug/equipe'
      preLoaderRoute: typeof GestaoSlugEquipeRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/extrato': {
      id: '/gestao/$slug/extrato'
      path: '/extrato'
      fullPath: '/gestao/$slug/extrato'
      preLoaderRoute: typeof GestaoSlugExtratoRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/pedidos': {
      id: '/gestao/$slug/pedidos'
      path: '/pedidos'
      fullPath: '/gestao/$slug/pedidos'
      preLoaderRoute: typeof GestaoSlugPedidosRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/produtos': {
      id: '/gestao/$slug/produtos'
      path: '/produtos'
      fullPath: '/gestao/$slug/produtos'
      preLoaderRoute: typeof GestaoSlugProdutosRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/recebimento': {
      id: '/gestao/$slug/recebimento'
      path: '/recebimento'
      fullPath: '/gestao/$slug/recebimento'
      preLoaderRoute: typeof GestaoSlugRecebimentoRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/repasses': {
      id: '/gestao/$slug/repasses'
      path: '/repasses'
      fullPath: '/gestao/$slug/repasses'
      preLoaderRoute: typeof GestaoSlugRepassesRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/gestao/$slug/resultado': {
      id: '/gestao/$slug/resultado'
      path: '/resultado'
      fullPath: '/gestao/$slug/resultado'
      preLoaderRoute: typeof GestaoSlugResultadoRouteImport
      parentRoute: typeof GestaoSlugRoute
    }
    '/loja/$slug/': {
      id: '/loja/$slug/'
      path: '/'
      fullPath: '/loja/$slug/'
      preLoaderRoute: typeof LojaSlugIndexRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/comprar': {
      id: '/loja/$slug/comprar'
      path: '/comprar'
      fullPath: '/loja/$slug/comprar'
      preLoaderRoute: typeof LojaSlugComprarRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/doar': {
      id: '/loja/$slug/doar'
      path: '/doar'
      fullPath: '/loja/$slug/doar'
      preLoaderRoute: typeof LojaSlugDoarRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/campanhas/': {
      id: '/loja/$slug/campanhas/'
      path: '/campanhas'
      fullPath: '/loja/$slug/campanhas/'
      preLoaderRoute: typeof LojaSlugCampanhasIndexRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/campanhas/$campanha': {
      id: '/loja/$slug/campanhas/$campanha'
      path: '/campanhas/$campanha'
      fullPath: '/loja/$slug/campanhas/$campanha'
      preLoaderRoute: typeof LojaSlugCampanhasCampanhaRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/e/$evento': {
      id: '/loja/$slug/e/$evento'
      path: '/e/$evento'
      fullPath: '/loja/$slug/e/$evento'
      preLoaderRoute: typeof LojaSlugEEventoRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/p/$produto': {
      id: '/loja/$slug/p/$produto'
      path: '/p/$produto'
      fullPath: '/loja/$slug/p/$produto'
      preLoaderRoute: typeof LojaSlugPProdutoRouteImport
      parentRoute: typeof LojaSlugRoute
    }
  }
}

interface GestaoSlugRouteChildren {
  GestaoSlugAgendaRoute: typeof GestaoSlugAgendaRoute
  GestaoSlugCampanhasRoute: typeof GestaoSlugCampanhasRoute
  GestaoSlugConfiguracoesRoute: typeof GestaoSlugConfiguracoesRoute
  GestaoSlugDoacoesRoute: typeof GestaoSlugDoacoesRoute
  GestaoSlugEncomendasRoute: typeof GestaoSlugEncomendasRoute
  GestaoSlugEquipeRoute: typeof GestaoSlugEquipeRoute
  GestaoSlugExtratoRoute: typeof GestaoSlugExtratoRoute
  GestaoSlugPedidosRoute: typeof GestaoSlugPedidosRoute
  GestaoSlugProdutosRoute: typeof GestaoSlugProdutosRoute
  GestaoSlugRecebimentoRoute: typeof GestaoSlugRecebimentoRoute
  GestaoSlugRepassesRoute: typeof GestaoSlugRepassesRoute
  GestaoSlugResultadoRoute: typeof GestaoSlugResultadoRoute
  GestaoSlugIndexRoute: typeof GestaoSlugIndexRoute
}

const GestaoSlugRouteChildren: GestaoSlugRouteChildren = {
  GestaoSlugAgendaRoute: GestaoSlugAgendaRoute,
  GestaoSlugCampanhasRoute: GestaoSlugCampanhasRoute,
  GestaoSlugConfiguracoesRoute: GestaoSlugConfiguracoesRoute,
  GestaoSlugDoacoesRoute: GestaoSlugDoacoesRoute,
  GestaoSlugEncomendasRoute: GestaoSlugEncomendasRoute,
  GestaoSlugEquipeRoute: GestaoSlugEquipeRoute,
  GestaoSlugExtratoRoute: GestaoSlugExtratoRoute,
  GestaoSlugPedidosRoute: GestaoSlugPedidosRoute,
  GestaoSlugProdutosRoute: GestaoSlugProdutosRoute,
  GestaoSlugRecebimentoRoute: GestaoSlugRecebimentoRoute,
  GestaoSlugRepassesRoute: GestaoSlugRepassesRoute,
  GestaoSlugResultadoRoute: GestaoSlugResultadoRoute,
  GestaoSlugIndexRoute: GestaoSlugIndexRoute,
}

const GestaoSlugRouteWithChildren = GestaoSlugRoute._addFileChildren(
  GestaoSlugRouteChildren,
)

interface LojaSlugRouteChildren {
  LojaSlugComprarRoute: typeof LojaSlugComprarRoute
  LojaSlugDoarRoute: typeof LojaSlugDoarRoute
  LojaSlugIndexRoute: typeof LojaSlugIndexRoute
  LojaSlugCampanhasCampanhaRoute: typeof LojaSlugCampanhasCampanhaRoute
  LojaSlugEEventoRoute: typeof LojaSlugEEventoRoute
  LojaSlugPProdutoRoute: typeof LojaSlugPProdutoRoute
  LojaSlugCampanhasIndexRoute: typeof LojaSlugCampanhasIndexRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugComprarRoute: LojaSlugComprarRoute,
  LojaSlugDoarRoute: LojaSlugDoarRoute,
  LojaSlugIndexRoute: LojaSlugIndexRoute,
  LojaSlugCampanhasCampanhaRoute: LojaSlugCampanhasCampanhaRoute,
  LojaSlugEEventoRoute: LojaSlugEEventoRoute,
  LojaSlugPProdutoRoute: LojaSlugPProdutoRoute,
  LojaSlugCampanhasIndexRoute: LojaSlugCampanhasIndexRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaRoute: ContaRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  LojasRoute: LojasRoute,
  NovaLojaRoute: NovaLojaRoute,
  PlataformaRoute: PlataformaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  GestaoSlugRoute: GestaoSlugRouteWithChildren,
  LojaSlugRoute: LojaSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
